# Scraped from Wikipedia: https://en.wikipedia.org/wiki/S%26P_100 as of 9/22/2025
snp100_tickers = {
    "AAPL",
    "ABBV",
    "ABT",
    "ACN",
    "ADBE",
    "AMAT",
    "AMD",
    "AMGN",
    "AMT",
    "AMZN",
    "AVGO",
    "AXP",
    "BA",
    "BAC",
    "BKNG",
    "BLK",
    "BMY",
    "BNY",
    "BRK.B",
    "C",
    "CAT",
    "CL",
    "CMCSA",
    "COF",
    "COP",
    "COST",
    "CRM",
    "CSCO",
    "CVS",
    "CVX",
    "DE",
    "DHR",
    "DIS",
    "DUK",
    "EMR",
    "FDX",
    "GD",
    "GE",
    "GEV",
    "GILD",
    "GM",
    "GOOG",
    "GOOGL",
    "GS",
    "HD",
    "HON",
    "IBM",
    "INTC",
    "INTU",
    "ISRG",
    "JNJ",
    "JPM",
    "KO",
    "LIN",
    "LLY",
    "LMT",
    "LOW",
    "LRCX",
    "MA",
    "MCD",
    "MDLZ",
    "MDT",
    "META",
    "MMM",
    "MO",
    "MRK",
    "MS",
    "MSFT",
    "MU",
    "NEE",
    "NFLX",
    "NKE",
    "NOW",
    "NVDA",
    "ORCL",
    "PEP",
    "PFE",
    "PG",
    "PLTR",
    "PM",
    "QCOM",
    "RTX",
    "SBUX",
    "SCHW",
    "SO",
    "SPG",
    "T",
    "TMO",
    "TMUS",
    "TSLA",
    "TXN",
    "UBER",
    "UNH",
    "UNP",
    "UPS",
    "USB",
    "V",
    "VZ",
    "WFC",
    "WMT",
    "XOM"
}

snp10_tickers=TOP10 = {
    "MSFT",
    "NVDA",
    "AAPL",
    "AMZN",
    "GOOGL",
    "META",
    "BRK.B",
    "AVGO",
    "TSLA",
    "JPM"
}


properties_to_query = [
    {"id": "P1056", "label": "product or material produced", "target_type": "Offering"},
    {"id": "P127",  "label": "owned by", "target_type": "Entity"},
    {"id": "P169",  "label": "chief executive officer", "target_type": "Person"},
    {"id": "P1830", "label": "owner of", "target_type": "Entity"},
    {"id": "P355",  "label": "child organization or unit", "target_type": "Entity"},
    {"id": "P361",  "label": "part of", "target_type": "Entity"},
    {"id": "P452",  "label": "industry", "target_type": "Entity"}
]
